language: ruby
rvm:
  - 2.5.1

sudo: false # use container-based infrastructure for a faster build

cache:
  bundler: true
  directories:
    - node_modules
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer # https://github.com/gjtorikian/html-proofer/issues/381

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  ssh_known_hosts: 
    - kjaermaxi.me
    - kjaer.io
  apt:
    packages:
    - graphviz              # to compile graphs to svg
    - libcurl4-openssl-dev  # to avoid SSL errors

before_install:
  - bash _scripts/install.sh

jobs:
  include:
    - stage: build
      name: Jekyll build
      script: bash _scripts/build.sh
    - stage: test
      name: Test HTML
      script: bash _scripts/test.sh
    - stage: test
      name: Optimize
      script: bash _scripts/optimize.sh
    - stage: deploy
      name: Deploy
      script: bash _scripts/deploy.sh

