language: ruby
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: NnIMF9H9Iv/2XXCZOkpYxqkItmib/UjLpy3MNmhidzpxOwlmZZZ/ZLJSXeTD+9YCqz0eBwQ3MlIlGXiHyrqqvTAt9fw6dEaeCbw0wgYxTaC3DsOaAzutwiK1uJ8EHWjDxqWLQqiN4cDf7G9PmJAk+0+JH64fsREH5xd/9TqwXMWsOp89TYhjP2yFZgsuJwIHiTweFraZ/PWHwVPpVkQNZO2uzyrbLbv1ZZzR68qxsiWBGvYTJ4K18dP58GofGPw53Y/Qyzv4/yT9dJ1StzT1ma7NQgyy0KwshTqe/NI3m5gkZ/RacVTTcJwMwaHAoIZ+AJeqr1nipByiaGaxQtdEHIaARGmHYmVfN/oD1rlQZ8ftAjScphdkqU0zpDX48IKgN7wf2jyhYJzAJrAn2vOlJOcibt5gD8QftTAdN5VMTcqfQ6JSf8C5nB0hzRpbNhALxY8ZVTphVLalnzwp+3MpD0f/D+CIFu3MGwdBRShwRJhLbeN1R8pXqoeRtjRuPEj2eFA+ndwoZNHPZFzH2/BLusiGnhDd/9pi1PQyHzU0pyXl8EQeGMoukXuWRlbKjs994S6wAvc812XMPyRpiDHEOtPG2C3Uth8r1QX6hwkEy6IR0KX4PUC8yOU1yAn0r3UCbYU4jF3ej70uPeuCTkHBV2vY4Nil9OHVDbSWp3Oza8I=
addons:
  ssh_known_hosts: kjaermaxi.me
before_install:
- _scripts/install.sh
script:
- _scripts/build.sh
- _scripts/test.sh
after_success:
- _scripts/deploy.sh
