language: ruby

cache:
  bundler: true
  directories:
    - node_modules

addons:
  ssh_known_hosts:
    - kjaermaxi.me
    - kjaer.io
  apt:
    packages:
      - graphviz # to compile graphs to svg
      - libcurl4-openssl-dev # to avoid SSL errors

before_install:
  - bash _scripts/install.sh

script:
  - npm run build
  - npm run optimize

deploy:
  provider: script
  script: bash _scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
