#########################
### BASIC INFORMATION ###
#########################

# The name of the site.
# Written in big on top of the hero image, and used in page titles.
name: OUTPUT

# A subtitle for the site.
# Written below the site's name, and next to it in the page title.
subtitle: The blog of Maxime Kjaer

# A default description for the site. 
# Used by search engines, Facebook and Twitter. Overridden by blog posts' description when possible.
description: "Maxime Kjaer's blog posts about the Web, software & technology. Most likely in that order."

# Your website URL
# Used in sitemap.xml and feed.xml
url: https://kjaer.io

# Information about the author. Used in feed.xml
author:
  name: Maxime Kjaer
  email: maxime.kjaer@gmail.com
  twitter: "@maximekjaer"
  url: https://kjaer.io

# Your disqus shortname. Entering this will enable commenting on posts by default
disqus: kjaermaxime

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-59915030-2

# Data for the hero image
hero:
  image: /images/hero/trees.jpg # The relative path to the default hero image
  fallback-color: "#d3dbe7" # The fallback color that will be used behind the image
  breakpoints: # Responsive image breakpoints. Important that these be in decreasing order!
    - 1440px
    - 1200px
    - 800px
    - 550px
    - 380px

# The URL of your GitHub repo
github: https://github.com/MaximeKjaer/kjaer.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


##############################
### ADVANCED OPTIONS BELOW ###
##############################

markdown: kramdown
highlighter: rouge
permalink: /:title/

excerpt_separator: "<!--"

sass:
  sass_dir: _sass
  style: :compressed # Can also be :expanded

# Use the following gems when building the site
gems:
  - jekyll-sitemap # Automatically create a sitemap on build

prose:
  rooturl: '_posts'
  siteurl: https://kjaer.io
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
      - name: image
        field:
          element: text
          label: Cover Image
          help: "/images/hero/trees.jpg, for example"
      - name: fallback-color
        field:
          element: text
          label: Fallback color
          help: "The color that will be behind the cover image as it loads. For the best effect, choose the average color of the cover image."
          value: "#0f45b7"
      - name: description
        field:
          element: textarea
          label: Description
      - name: comments
        field:
          element: button
          on: Comments enabled
          off: Comments disabled


defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      published: true
      comments: true
      unlisted: false
      edited: false

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - nohup.out
  - npm-debug.log
  - node_modules
  - package.json
  - README.md
  - serve.bat
  - vendor
  - zopfli
