title: OUTPUT
subtitle: The blog of Maxime Kjaer
description: "Maxime Kjaer's blog posts about the Web, software & technology. Most likely in that order."
name: Maxime Kjaer
hero_image: /images/hero/trees.jpg

#
# Flags below are optional
#

author:
  name: Maxime Kjaer
  email: maxime.kjaer@gmail.com
  twitter: "@maximekjaer"
  uri: https://kjaer.io

# Your disqus shortname, entering this will enable commenting on posts
disqus: kjaermaxime

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-59915030-2

image_breakpoints: # Important that these be in decreasing order!
  - 1440px
  - 1200px
  - 800px
  - 550px
  - 380px

# The URL of your GitHub repo
github: https://github.com/MaximeKjaer/kjaer.io

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: https://kjaer.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /:title/

excerpt_separator: "<!--"

sass:
  sass_dir: _sass
  # style: :expanded # It's either :compressed or :expanded.
  style: :compressed

# Use the following gems when building the site
gems:
  - jekyll-sitemap

prose:
  rooturl: '_posts'
  siteurl: https://kjaer.io
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
      - name: image
        field:
          element: text
          label: Cover Image
          help: "/images/hero/trees.jpg, for example"
      - name: fallback-color
        field:
          element: text
          label: Fallback color
          help: "The color that will be behind the cover image as it loads. For the best effect, choose the average color of the cover image."
          value: "#0f45b7"
      - name: description
        field:
          element: textarea
          label: Description
      - name: comments
        field:
          element: button
          on: Comments enabled
          off: Comments disabled


defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      comments: true
      unlisted: false

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - nohup.out
  - npm-debug.log
  - node_modules
  - package.json
  - README.md
  - serve.bat
  - vendor
  - zopfli
