title: OUTPUT
subtitle: The blog of Maxime Kjaer
description: "Maxime Kjaer's blog posts about the Web, software & technology. Most likely in that order."
name: Maxime Kjaer
hero_image: /images/trees.jpg

#
# Flags below are optional
#

author:
  name: Maxime Kjaer
  email: maxime.kjaer@gmail.com
  twitter: "@maximekjaer"
  uri: http://kjaermaxi.me

# Your disqus shortname, entering this will enable commenting on posts
disqus: kjaermaxime

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-59915030-2

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: http://kjaermaxi.me

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /:title/

excerpt_separator: "<!--"

sass:
  sass_dir: _sass
  # style: :expanded # It's either :compressed or :expanded.
  style: :compressed

# Use the following gems when building the site
gems:
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - nohup.out
  - npm-debug.log
  - package.json
  - README.md
  - serve.bat
  - vendor
  - zopfli
